language: java
jdk: oraclejdk8
addons:
  apt:
      packages:
          - sshpass
after_success:
  - export SSHPASS=$DEPLOY_PASSWORD
  - export ENVIRONMENT_NAME=preprod
  - test $TRAVIS_BRANCH = "prod" && export ENVIRONMENT_NAME=prod
  - sshpass -e scp -o stricthostkeychecking=no target/website.jar qualityirrelevant@qualityirrelevant.com:/home/qualityirrelevant/$ENVIRONMENT_NAME
  - sshpass -e ssh -o stricthostkeychecking=no -n -f qualityirrelevant@qualityirrelevant.com "sudo systemctl restart qualityirrelevant-$ENVIRONMENT_NAME"