language: java
jdk: oraclejdk8
after_success:
  - export SSHPASS=$DEPLOY_PASSWORD
  - sshpass -e scp target/website.jar qualityirrelevant@qualityirrelevant.com:~/
  - sshpass -e ssh qualityirrelevant@qualityirrelevant.com ~/deploy.sh