language: java
jdk: oraclejdk8
addons:
  apt:
      packages:
          - sshpass
after_success:
  - export SSHPASS=$DEPLOY_PASSWORD
  - sshpass -e scp -o stricthostkeychecking=no target/website.jar qualityirrelevant@qualityirrelevant.com:/home/qualityirrelevant
  - sshpass -e ssh -o stricthostkeychecking=no qualityirrelevant@qualityirrelevant.com /home/qualityirrelevant/deploy.sh